/*
 * gpio_starter.c
 *
 *  Created on: 18 oct. 2019
 *      Author: exo
 */
#include "headers/gpio_starter.h"
#include <DR_pinsel.h>
#include <DR_gpio.h>

void init_gpio() {
	SetPINSEL(RELAY1,FUNCION_GPIO);
	SetPINSEL(RELAY2,FUNCION_GPIO);
	SetPINSEL(RELAY3,FUNCION_GPIO);
	SetPINSEL(RELAY4,FUNCION_GPIO);
	SetPINSEL(LED6,FUNCION_GPIO);
	SetPINSEL(LED1,FUNCION_GPIO);
	SetPINSEL(LED8,FUNCION_GPIO);
	SetPINSEL(IN0,FUNCION_GPIO);
	SetPINSEL(IN1,FUNCION_GPIO);
	SetPINSEL(IN2,FUNCION_GPIO);

	SetPINSEL(SW1,FUNCION_GPIO);
	SetPINSEL(SW4,FUNCION_GPIO);
	SetPINSEL(SW7,FUNCION_GPIO);
	SetPINSEL(SW10,FUNCION_GPIO);
	SetPINSEL(SW13,FUNCION_GPIO);

	SetDIR( RELAY1 , SALIDA);
	SetDIR( RELAY2 , SALIDA);
	SetDIR( RELAY3 , SALIDA);
	SetDIR( RELAY4 , SALIDA);
	SetDIR( LED6 , SALIDA);
	SetDIR( LED1 , SALIDA);
	SetDIR( LED8 , SALIDA);
	SetDIR( IN0 , ENTRADA);
	SetDIR( IN1 , ENTRADA);
	SetDIR( IN2 , ENTRADA);
	SetDIR( SW1, ENTRADA);
	SetDIR( SW4, ENTRADA);
	SetDIR( SW7, ENTRADA);
	SetDIR( SW10, ENTRADA);
	SetDIR( SW13, ENTRADA);

	SetMODE(IN0,PULLUP);
	SetMODE(IN1,PULLUP);
	SetMODE(IN2,PULLUP);
	SetMODE(SW1,PULLUP);
	SetMODE(SW4,PULLUP);

	SetPIN(RELAY1,OFF);
	SetPIN(RELAY2,OFF);
	SetPIN(RELAY3,OFF);
	SetPIN(RELAY4,OFF);
	SetPIN(LED6,OFF);
	SetPIN(LED1,OFF);
	SetPIN(LED8,OFF);
}


